version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Corrected port mapping: host port 8080 to container port 8080
    volumes:
      - ./:/app
